//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Nullable<int> student_id { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> amount { get; set; }
        public int purchase_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Student Student { get; set; }
    }
}
